// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLTTDT.Data;

#nullable disable

namespace QLTTDT.Migrations
{
    [DbContext(typeof(QLTTDTDbContext))]
    [Migration("20250415144902_unicode-capdo")]
    partial class unicodecapdo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLTTDT.Models.CapDo", b =>
                {
                    b.Property<int>("MaCapDo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCapDo"));

                    b.Property<string>("TenCapDo")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("MaCapDo")
                        .HasName("PK__CapDo__40B881FC34CD938B");

                    b.ToTable("CapDo");
                });

            modelBuilder.Entity("QLTTDT.Models.ChuDe", b =>
                {
                    b.Property<int>("MaChuDe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChuDe"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("TenChuDe")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)");

                    b.HasKey("MaChuDe")
                        .HasName("PK__ChuDe__358545113217E9F1");

                    b.ToTable("ChuDe");
                });

            modelBuilder.Entity("QLTTDT.Models.DangKiKhoaHoc", b =>
                {
                    b.Property<int>("MaDangKi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDangKi"));

                    b.Property<bool?>("DaHuy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("MaHocVien")
                        .HasColumnType("int");

                    b.Property<int>("MaKhoaHoc")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianDangKi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MaDangKi")
                        .HasName("PK__DangKiKh__BA90F03DA183D1E4");

                    b.HasIndex("MaHocVien");

                    b.HasIndex("MaKhoaHoc");

                    b.ToTable("DangKiKhoaHoc");
                });

            modelBuilder.Entity("QLTTDT.Models.KhoaHoc", b =>
                {
                    b.Property<int>("MaKhoaHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhoaHoc"));

                    b.Property<int>("HocPhi")
                        .HasColumnType("int");

                    b.Property<int>("MaCapDo")
                        .HasColumnType("int");

                    b.Property<int>("MaChuDe")
                        .HasColumnType("int");

                    b.Property<int>("MaGiangVien")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("SoLuongHocVienToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenKhoaHoc")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime>("ThoiGianKhaiGiang")
                        .HasColumnType("datetime");

                    b.Property<string>("UrlAnh")
                        .HasMaxLength(1024)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1024)");

                    b.HasKey("MaKhoaHoc")
                        .HasName("PK__KhoaHoc__48F0FF9810CE4F86");

                    b.HasIndex("MaCapDo");

                    b.HasIndex("MaChuDe");

                    b.HasIndex("MaGiangVien");

                    b.ToTable("KhoaHoc");
                });

            modelBuilder.Entity("QLTTDT.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateOnly>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("UrlAnhDaiDien")
                        .HasMaxLength(1024)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1024)");

                    b.HasKey("MaNguoiDung")
                        .HasName("PK__NguoiDun__C539D762DEB4CD35");

                    b.HasIndex(new[] { "SoDienThoai" }, "UQ__NguoiDun__0389B7BDB0A369DA")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__NguoiDun__A9D10534C87B5570")
                        .IsUnique();

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("QLTTDT.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)");

                    b.HasKey("MaTaiKhoan")
                        .HasName("PK__TaiKhoan__AD7C65292DD8A25F");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaVaiTro");

                    b.HasIndex(new[] { "TenDangNhap" }, "UQ__TaiKhoan__55F68FC0D1D67C41")
                        .IsUnique();

                    b.HasIndex(new[] { "Salt" }, "UQ__TaiKhoan__A152BCCEA20E915F")
                        .IsUnique();

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("QLTTDT.Models.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("MaVaiTro")
                        .HasName("PK__VaiTro__C24C41CFAB44AE39");

                    b.ToTable("VaiTro");
                });

            modelBuilder.Entity("QLTTDT.Models.DangKiKhoaHoc", b =>
                {
                    b.HasOne("QLTTDT.Models.NguoiDung", "MaHocVienNavigation")
                        .WithMany("DangKiKhoaHocs")
                        .HasForeignKey("MaHocVien")
                        .IsRequired()
                        .HasConstraintName("FK_DangKiKhoaHoc_NguoiDung");

                    b.HasOne("QLTTDT.Models.KhoaHoc", "MaKhoaHocNavigation")
                        .WithMany("DangKiKhoaHocs")
                        .HasForeignKey("MaKhoaHoc")
                        .IsRequired()
                        .HasConstraintName("FK_DangKiKhoaHoc_KhoaHoc");

                    b.Navigation("MaHocVienNavigation");

                    b.Navigation("MaKhoaHocNavigation");
                });

            modelBuilder.Entity("QLTTDT.Models.KhoaHoc", b =>
                {
                    b.HasOne("QLTTDT.Models.CapDo", "MaCapDoNavigation")
                        .WithMany("KhoaHocs")
                        .HasForeignKey("MaCapDo")
                        .IsRequired()
                        .HasConstraintName("FK_KhoaHoc_CapDo");

                    b.HasOne("QLTTDT.Models.ChuDe", "MaChuDeNavigation")
                        .WithMany("KhoaHocs")
                        .HasForeignKey("MaChuDe")
                        .IsRequired()
                        .HasConstraintName("FK_KhoaHoc_ChuDe");

                    b.HasOne("QLTTDT.Models.NguoiDung", "MaGiangVienNavigation")
                        .WithMany("KhoaHocs")
                        .HasForeignKey("MaGiangVien")
                        .IsRequired()
                        .HasConstraintName("FK_KhoaHoc_NguoiDung");

                    b.Navigation("MaCapDoNavigation");

                    b.Navigation("MaChuDeNavigation");

                    b.Navigation("MaGiangVienNavigation");
                });

            modelBuilder.Entity("QLTTDT.Models.TaiKhoan", b =>
                {
                    b.HasOne("QLTTDT.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("MaNguoiDung")
                        .IsRequired()
                        .HasConstraintName("FK_TaiKhoan_NguoiDung");

                    b.HasOne("QLTTDT.Models.VaiTro", "MaVaiTroNavigation")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("MaVaiTro")
                        .IsRequired()
                        .HasConstraintName("FK_TaiKhoan_VaiTro");

                    b.Navigation("MaNguoiDungNavigation");

                    b.Navigation("MaVaiTroNavigation");
                });

            modelBuilder.Entity("QLTTDT.Models.CapDo", b =>
                {
                    b.Navigation("KhoaHocs");
                });

            modelBuilder.Entity("QLTTDT.Models.ChuDe", b =>
                {
                    b.Navigation("KhoaHocs");
                });

            modelBuilder.Entity("QLTTDT.Models.KhoaHoc", b =>
                {
                    b.Navigation("DangKiKhoaHocs");
                });

            modelBuilder.Entity("QLTTDT.Models.NguoiDung", b =>
                {
                    b.Navigation("DangKiKhoaHocs");

                    b.Navigation("KhoaHocs");

                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("QLTTDT.Models.VaiTro", b =>
                {
                    b.Navigation("TaiKhoans");
                });
#pragma warning restore 612, 618
        }
    }
}
